name: serti0x
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #! LINTERS
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.6
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
