name: serti0x
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #!STATE MANAGEMENT AND SUPPORTING UTILS
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3

  #! ALL UTILS
  intl: ^0.19.0
  flutter_screenutil: ^5.8.3
  flutter_svg_provider: ^1.0.7

  #! ANIMATIONS
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #! LINTERS
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.6
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Italic.ttf
